package com.example.transactionstarter;

import java.math.BigDecimal;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.example.transactionstarter.dto.UpdateTransactionStatusRequest;
import com.example.transactionstarter.enums.Currency;
import com.example.transactionstarter.enums.TransactionStatus;
import com.example.transactionstarter.enums.TransactionType;
import com.example.transactionstarter.model.Transaction;
import com.example.transactionstarter.repository.TransactionRepository;
import com.fasterxml.jackson.databind.ObjectMapper;

@SpringBootTest
@AutoConfigureMockMvc
class TransactionStarterApplicationTests {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private TransactionRepository transactionRepository;

    @Autowired
    private ObjectMapper objectMapper;

    @BeforeEach
    void setUp() {
        transactionRepository.deleteAll();
    }

    @Test
    void testCreateAndGetAllTransactions() throws Exception {
        Transaction transaction = new Transaction(
                "TXN-101",
                "CUST-001",
                new BigDecimal("150.00"),
                Currency.USD,
                TransactionType.PAYMENT,
                TransactionStatus.COMPLETED
        );

        mockMvc.perform(post("/transactions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(transaction)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.transactionId").value("TXN-101"))
                .andExpect(jsonPath("$.customerId").value("CUST-001"));

        mockMvc.perform(get("/transactions"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.length()").value(1));
    }

    @Test
    void testCreateTransaction_AutoGeneratedId() throws Exception {
        Transaction transaction = new Transaction(
                null,
                "CUST-001",
                new BigDecimal("250.00"),
                Currency.USD,
                TransactionType.PAYMENT,
                TransactionStatus.COMPLETED
        );

        mockMvc.perform(post("/transactions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(transaction)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.transactionId").value("TXN-001"))
                .andExpect(jsonPath("$.customerId").value("CUST-001"));
    }

    @Test
    void testGetTransactionById() throws Exception {
        Transaction t1 = new Transaction("TXN-1", "CUST-101", new BigDecimal("100.00"), Currency.INR, TransactionType.DEPOSIT, TransactionStatus.COMPLETED);
        transactionRepository.save(t1);

        mockMvc.perform(get("/transactions/TXN-1"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.transactionId").value("TXN-1"))
                .andExpect(jsonPath("$.customerId").value("CUST-101"));
    }

    @Test
    void testGetTransactionsByCustomerId() throws Exception {
        Transaction t1 = new Transaction("TXN-1", "CUST-101", new BigDecimal("100.00"), Currency.INR, TransactionType.DEPOSIT, TransactionStatus.COMPLETED);
        Transaction t2 = new Transaction("TXN-2", "CUST-102", new BigDecimal("200.00"), Currency.EUR, TransactionType.WITHDRAWAL, TransactionStatus.PENDING);
        transactionRepository.save(t1);
        transactionRepository.save(t2);

        mockMvc.perform(get("/transactions/customer/CUST-101"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.length()").value(1))
                .andExpect(jsonPath("$[0].transactionId").value("TXN-1"))
                .andExpect(jsonPath("$[0].customerId").value("CUST-101"));
    }

    @Test
    void testUpdateTransaction() throws Exception {
        Transaction t1 = new Transaction("TXN-1", "CUST-101", new BigDecimal("100.00"), Currency.INR, TransactionType.DEPOSIT, TransactionStatus.COMPLETED);
        transactionRepository.save(t1);

        Transaction update = new Transaction("TXN-1", "CUST-101", new BigDecimal("500.00"), Currency.INR, TransactionType.DEPOSIT, TransactionStatus.COMPLETED);

        mockMvc.perform(put("/transactions/TXN-1")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(update)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.amount").value(500.00));
    }

    @Test
    void testUpdateTransactionStatus_Success() throws Exception {
        Transaction t1 = new Transaction("TXN-1", "CUST-101", new BigDecimal("100.00"), Currency.INR, TransactionType.DEPOSIT, TransactionStatus.PENDING);
        transactionRepository.save(t1);

        UpdateTransactionStatusRequest request = new UpdateTransactionStatusRequest();
        request.setTransactionStatus(TransactionStatus.PROCESSING);

        mockMvc.perform(patch("/transactions/TXN-1/status")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.transactionStatus").value("PROCESSING"));
    }

    @Test
    void testGetTransactionsByCustomerId_NotFound() throws Exception {
        mockMvc.perform(get("/transactions/customer/NON_EXISTENT_CUST"))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.message").value("Customer not found with id: NON_EXISTENT_CUST"))
                .andExpect(jsonPath("$.status").value(404));
    }
}
