package com.example.transactionstarter;

import java.math.BigDecimal;
import java.util.UUID;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.example.transactionstarter.dto.CreateTransactionRequest;
import com.example.transactionstarter.dto.UpdateTransactionStatusRequest;
import com.example.transactionstarter.enums.Currency;
import com.example.transactionstarter.enums.TransactionStatus;
import com.example.transactionstarter.enums.TransactionType;
import com.example.transactionstarter.model.Transaction;
import com.example.transactionstarter.repository.TransactionRepository;
import com.fasterxml.jackson.databind.ObjectMapper;

@SpringBootTest
@AutoConfigureMockMvc
class TransactionStarterApplicationTests {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private TransactionRepository transactionRepository;

    @Autowired
    private ObjectMapper objectMapper;

    @BeforeEach
    void setUp() {
        transactionRepository.deleteAll();
    }

    @Test
    void testCreateAndGetAllTransactions() throws Exception {

        CreateTransactionRequest request
                = new CreateTransactionRequest();

        request.setCustomerId("CUST-001");
        request.setAmount(new BigDecimal("150.00"));
        request.setCurrency(Currency.USD);
        request.setTransactionType(TransactionType.PAYMENT);

        String response = mockMvc.perform(post("/transactions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.customerId").value("CUST-001"))
                .andExpect(jsonPath("$.amount").value(150.00))
                .andExpect(jsonPath("$.currency").value("USD"))
                .andExpect(jsonPath("$.transactionType").value("PAYMENT"))
                .andExpect(jsonPath("$.transactionStatus").value("PENDING"))
                .andReturn()
                .getResponse()
                .getContentAsString();

        // Verify that transactionId is a valid UUID
        Transaction created
                = objectMapper.readValue(response, Transaction.class);

        UUID.fromString(created.getTransactionId());

        mockMvc.perform(get("/transactions"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.length()").value(1));
    }

    @Test
    void testCreateTransaction_AutoGeneratedUuid() throws Exception {

        CreateTransactionRequest request
                = new CreateTransactionRequest();

        request.setCustomerId("CUST-001");
        request.setAmount(new BigDecimal("250.00"));
        request.setCurrency(Currency.USD);
        request.setTransactionType(TransactionType.PAYMENT);

        String response = mockMvc.perform(post("/transactions")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.customerId").value("CUST-001"))
                .andExpect(jsonPath("$.transactionStatus").value("PENDING"))
                .andReturn()
                .getResponse()
                .getContentAsString();

        Transaction created
                = objectMapper.readValue(response, Transaction.class);

        // UUID.fromString() throws an exception if the ID is not a valid UUID
        UUID.fromString(created.getTransactionId());
    }

    @Test
    void testGetTransactionById() throws Exception {

        String transactionId = UUID.randomUUID().toString();

        Transaction transaction = new Transaction(
                transactionId,
                "CUST-101",
                new BigDecimal("100.00"),
                Currency.INR,
                TransactionType.DEPOSIT,
                TransactionStatus.COMPLETED
        );

        transactionRepository.save(transaction);

        mockMvc.perform(get("/transactions/" + transactionId))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.transactionId").value(transactionId))
                .andExpect(jsonPath("$.customerId").value("CUST-101"));
    }

    @Test
    void testGetTransactionsByCustomerId() throws Exception {

        String transactionId1 = UUID.randomUUID().toString();
        String transactionId2 = UUID.randomUUID().toString();

        Transaction t1 = new Transaction(
                transactionId1,
                "CUST-101",
                new BigDecimal("100.00"),
                Currency.INR,
                TransactionType.DEPOSIT,
                TransactionStatus.COMPLETED
        );

        Transaction t2 = new Transaction(
                transactionId2,
                "CUST-102",
                new BigDecimal("200.00"),
                Currency.EUR,
                TransactionType.WITHDRAWAL,
                TransactionStatus.PENDING
        );

        transactionRepository.save(t1);
        transactionRepository.save(t2);

        mockMvc.perform(get("/transactions/customer/CUST-101"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.length()").value(1))
                .andExpect(jsonPath("$[0].transactionId").value(transactionId1))
                .andExpect(jsonPath("$[0].customerId").value("CUST-101"));
    }

    @Test
    void testUpdateTransaction() throws Exception {

        String transactionId = UUID.randomUUID().toString();

        Transaction existing = new Transaction(
                transactionId,
                "CUST-101",
                new BigDecimal("100.00"),
                Currency.INR,
                TransactionType.DEPOSIT,
                TransactionStatus.PENDING
        );

        transactionRepository.save(existing);

        Transaction update = new Transaction(
                transactionId,
                "CUST-101",
                new BigDecimal("500.00"),
                Currency.INR,
                TransactionType.DEPOSIT,
                TransactionStatus.PROCESSING
        );

        mockMvc.perform(put("/transactions/" + transactionId)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(update)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.transactionId").value(transactionId))
                .andExpect(jsonPath("$.amount").value(500.00))
                .andExpect(jsonPath("$.transactionStatus").value("PROCESSING"));
    }

    @Test
    void testUpdateTransactionStatus_Success() throws Exception {

        String transactionId = UUID.randomUUID().toString();

        Transaction transaction = new Transaction(
                transactionId,
                "CUST-101",
                new BigDecimal("100.00"),
                Currency.INR,
                TransactionType.DEPOSIT,
                TransactionStatus.PENDING
        );

        transactionRepository.save(transaction);

        UpdateTransactionStatusRequest request
                = new UpdateTransactionStatusRequest();

        request.setTransactionStatus(TransactionStatus.PROCESSING);

        mockMvc.perform(patch("/transactions/" + transactionId + "/status")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.transactionId").value(transactionId))
                .andExpect(jsonPath("$.transactionStatus").value("PROCESSING"));
    }

    @Test
    void testUpdateTransactionStatus_InvalidTransition() throws Exception {

        String transactionId = UUID.randomUUID().toString();

        Transaction transaction = new Transaction(
                transactionId,
                "CUST-101",
                new BigDecimal("100.00"),
                Currency.INR,
                TransactionType.DEPOSIT,
                TransactionStatus.COMPLETED
        );

        transactionRepository.save(transaction);

        UpdateTransactionStatusRequest request
                = new UpdateTransactionStatusRequest();

        request.setTransactionStatus(TransactionStatus.PENDING);

        mockMvc.perform(patch("/transactions/" + transactionId + "/status")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isBadRequest());
    }

    @Test
    void testGetTransactionsByCustomerId_NotFound() throws Exception {

        mockMvc.perform(get("/transactions/customer/NON_EXISTENT_CUST"))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.message")
                        .value("No transactions found for customer id: NON_EXISTENT_CUST"))
                .andExpect(jsonPath("$.status").value(404));
    }
}
